### ISSUE TITLE
Sometimes after answering right questions , the application stop and prevent me to answer the next question

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Brainee-B2C#32]

**Comment by MNenaey** [comment]
system stopped

![image.png](https://images.zenhubusercontent.com/5bfa9a848ffeb454062a0422/9b5d40f0-1b8f-42ba-b2eb-f0800ae6bfbb)

**Comment by alweshahi** [comment]
I can't catch it - working fine every time

**Comment by MNenaey** [comment]
I tried it many times it happened once 
we can close it for now
